### PR TITLE
Add synchronisation to wait for goroutine completion

### PR DESCRIPTION
**Pull request by w-miller**
The new WaitForStop method waits for all goroutines spawned by a file or directory watcher to have terminated, giving applications a way to deterministically wait for resource cleanup to have completred after cancelling the passed context.

Add goleak checks to tests, verifying that no rogue goroutines are present at test teardown.

### CODE REVIEW

**Review by illarion — CHANGES_REQUESTED** [review]
Hello! Thank you for your interest. Anyway, what I've found is that goleak is missing from the go.mod file, causing build to fail. And another thing, maybe it would be better to expose a context that would be done, when the dirwatcher is finished? Like the dirwatcher itself could implement Context. And what about other watchers?

**Comment by w-miller** [comment]
@illarion thanks for your reply. I forgot to commit the go.sum file as it was untracked; I've fixed that now, so hopefully the workflow should run now.

Regarding your point about the watchers implementing `context.Context`, I've had a quick play with that but I'm not sure how feasible it would be. `context.Context`'s `Done()` method requires returning a channel that is closed when the work is completed, and the `Done()` method returns without blocking. But in order for the watcher's `Done()` to be able to do this, it would need to spawn a goroutine that waits for the other internal goroutines to have completed (e.g. with the waitgroup) and then close the channel, which I believe will always be inherently racy as it will have to close the channel (and thereby signal to the caller of `Done()` that all goroutines have terminated) before that goroutine itself has terminated. Unless I've misunderstood some part of your suggestion?

>And what about other watchers?

I've implemented it here for FileWatcher and DirWatcher. I didn't notice any other watchers in the repo - did I miss some?

**Comment by illarion** [comment]
Ok, so, please describe your use case, from the end user point of view. I think it would help me to understand better what is going on here and how we can implement this. Thank you!

**Comment by w-miller** [comment]
@illarion The use case is that we want to use a gonotify dirwatcher to monitor a directory as part of a server process. One of our best practices is to ensure that all objects we run in our servers pass when run under the `goleak` library. This verifies that all goroutines created by the object have been tidied up by the end of a test -- i.e. at a deterministic point in the object's lifecycle. Typically an object has some `New()`/`Start()` method (`NewDirWatcher()` in this case), which may spawn some internal goroutines. On shutdown, we expect to be able to call some `Stop()` method (in this PR, the combination of cancelling the watcher's context and then calling `WaitForStop()`). After this has returned, we expect to be guaranteed that all goroutines created in the object's `Start()` have exited, and goleak will fail the test if this is not the case.

**Comment by illarion** [comment]
I've implemented context.Context for Dir/File wathcers. You can simply wait for your watcher.Done(), please test if it fixes your issue

**Comment by illarion** [comment]
Reopened, need to add a few more things

**Comment by illarion** [comment]
@w-miller, unfortunately, I can't merge your PR, since it updates the minimal go version (I want to keep this lib as compatible as possible), and adds new dependency - goleak. 

But, I've implemented your proposal, just a little bit simpler - by utilizing waitgroup and context-like interface. File watcher and dirwatcher now have method Done(), that returns a channel. You can wait for this channel to get closed, just like you wait for context to get done.

If you want, you can test your application, that uses gonotify with goleak, before and after adding waiting for *Watcher.Done()

Thank you!

**Comment by w-miller** [comment]
Hi @illarion, thanks for your response. I've tested out your changes and have a few comments:

- When running the tests repeatedly with the race checker (`go test -count 10 -race -v ./...`) and with goleak enabled locally, I found an issue with [leaking an Inotify goroutine](https://github.com/illarion/gonotify/pull/7/commits/fa28ca120153f5a341d975ee3f306fa4b04d457e) since a refactor for [another fix](https://github.com/illarion/gonotify/commit/afb343cde463f0a90ea55bbd50f42dc199f6ad89), and also an issue with [logging after test completion](https://github.com/illarion/gonotify/pull/7/commits/a485a8770ca2cfa4b078325f940a56a5121fc8b2). I've opened [a PR](https://github.com/illarion/gonotify/pull/7) for these.

- When I add waiting for the `Done()` on the file/dir watchers to all relevant tests (as I did in this PR, and have also separated out into a [new draft PR](https://github.com/illarion/gonotify/pull/8)), some of the tests intermittently hang when run with a few repetitions, as the internal goroutines are blocking trying to write to the `events` channel but the ctx has been cancelled. I believe these problems will be occurring in your existing CI on `master` with internal goroutines sometimes hanging, just that the tests pass anyway because they're not waiting for `Done()` in `master`.  I also fixed the places where the goroutines would hang in this (now-closed) PR (e.g. [here](https://github.com/illarion/gonotify/pull/5/files#diff-5f13e701a378b35eb7bd3f55f6a7807bd8a1f42a4a620cc8645167711b71476cR141-R146)), but I don't think you included those changes in the fix you merged (e.g. no checking for `ctx.Done()` [here in `master`](https://github.com/illarion/gonotify/blob/master/dirwatcher.go#L139)).

**Pull request closed without merging**
